name: PR Validation

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - name: Lint HTML
        run: npx htmlhint ./src/**/*.html
      - name: Lint CSS
        run: npx stylelint "./styles/**/*.css"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - name: Build with Parcel
        run: npx parcel build src/index.html